[package]
name = "pg"
version = "0.1.0"
authors = ["Andrew Stephan <andrew@pointguard.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.9"
clap = "3.0.0-beta.1"
