name: Rust

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
    - name: Setup gpg
      run: |
        echo "${{secrets.GPG_PUBLIC_KEY}}" | gpg --import
        echo "${{secrets.GPG_PRIVATE_KEY}}" | gpg --import
        echo "${{secrets.GPG_OWNERTRUST}}" | gpg --import-ownertrust
        ./setup-tests.sh `gpg --list-keys --with-colons | awk -F: '/^fpr/ { print $10 }'`
    - name: Clippy
      run: cargo clippy
    - name: RustFmt
      run: cargo fmt -- --check
    - name: Run tests
      run: cargo test --verbose

  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      run: cargo build --verbose
